# Generated by Django 5.2.5 on 2025-08-19 18:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,10}$', 'Symbol must be uppercase alphanumeric (2-10 characters).')])),
                ('category', models.CharField(choices=[('gold', 'Gold'), ('coin', 'Coin'), ('currency', 'Currency'), ('crypto', 'Crypto')], db_index=True, default='currency', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceConfigModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='URL path for scraping (e.g., profile/price_dollar_rl)', max_length=255)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_configs', to='scraping.instrumentmodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_configs', to='scraping.sourcemodel')),
            ],
            options={
                'verbose_name': 'Source Config',
                'verbose_name_plural': 'Source Configs',
            },
        ),
        migrations.CreateModel(
            name='PriceTickModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('IRR', 'Iranian Rial')], db_index=True, default='IRR', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ticks', to='scraping.instrumentmodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ticks', to='scraping.sourcemodel')),
            ],
            options={
                'verbose_name': 'Price Tick',
                'verbose_name_plural': 'Price Ticks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timestamp'], name='scraping_pr_instrum_25c5d9_idx'), models.Index(fields=['source', 'timestamp'], name='scraping_pr_source__f31c1b_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'source', 'timestamp'), name='unique_instrument_source_timestamp')],
            },
        ),
    ]
