# Generated by Django 5.2.5 on 2025-08-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetickmodel',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
