# Generated by Django 5.2.5 on 2025-08-25 09:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('max_requests', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_reset_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'indexes': [models.Index(fields=['user_id'], name='bot_telegra_user_id_9fd9db_idx'), models.Index(fields=['username'], name='bot_telegra_usernam_ed3add_idx'), models.Index(fields=['status'], name='bot_telegra_status_a0c53c_idx'), models.Index(fields=['last_seen'], name='bot_telegra_last_se_774665_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('usage', 'Usage'), ('request', 'Request')], default='start', help_text='Type of command/action performed', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Raw message or description of the action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional JSON data for extra info, e.g., parameters or context', null=True)),
                ('telegram_user', models.ForeignKey(help_text='The Telegram user who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bot.telegramusermodel')),
            ],
            options={
                'verbose_name': 'Telegram Command',
                'verbose_name_plural': 'Telegram Commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_user'], name='bot_telegra_telegra_41a5a0_idx'), models.Index(fields=['command_type'], name='bot_telegra_command_c4bc45_idx'), models.Index(fields=['created_at'], name='bot_telegra_created_0f9f60_idx')],
            },
        ),
    ]
