# Generated by Django 5.2.5 on 2025-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramusermodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammessagemodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Telegram Message', 'verbose_name_plural': 'Telegram Messages'},
        ),
        migrations.RemoveField(
            model_name='telegrammessagemodel',
            name='recipient',
        ),
        migrations.AddField(
            model_name='telegrammessagemodel',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='messages', to='bot.telegramusermodel', verbose_name='Recipients (Leave empty for all)'),
        ),
    ]
