# Generated by Django 5.2.5 on 2025-09-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegrammessagemodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogViewer',
        ),
    ]
